name: PHP 7.4 Tests

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['7.4']

        name: PHP ${{ matrix.php }} tests

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: unit3d_test
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP 7.4
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
                    coverage: none

            -   name: Install Composer Dependencies
                run: composer install --no-progress --ansi
                if: "matrix.dependencies != 'lowest'"

            -   name: Update Composer Dependencies
                run: composer update --no-progress --ansi
                if: "matrix.dependencies == 'lowest'"

            -   name: Prepare UNIT3D Application
                run: |
                    cp .env.testing .env
                    php artisan key:generate

            -   name: Run UNIT3D PHPUnit Tests
                run: vendor/bin/phpunit
                env:
                    DB_PORT: ${{ job.services.mysql.ports[3306] }}
