name: PHP 7.4 Tests

on: [ push, pull_request ]

jobs:
    phpunit:
        name: "PHP ${{ matrix.php }} Tests"
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: true
                    MYSQL_DATABASE: UNIT3D
                    MYSQL_PASSWORD: UNIT3D
                    MYSQL_USER: UNIT3D
                ports:
                    - 3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 1

            - name: Setup PHP 7.4
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  tools: phpunit
                  extensions: gd, json, mbstring, mysql, dom, fileinfo, xml, xsl, zip, curl, bcmath, intl
                  coverage: none

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache Composer Dependencies
              uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install Composer Dependencies
              run: composer install --no-scripts --no-progress --no-suggest --prefer-dist --optimize-autoloader

            - name: Copy UNIT3D CI Environment
              run: cp .env.testing .env

            - name: Generate UNIT3D Key
              run: php artisan key:generate

            - name: Run UNIT3D Migrations
              run: php artisan migrate
              env:
                  DB_PORT: ${{ job.services.mysql.ports['3306'] }}

            - name: Run Testsuite
              run: ./vendor/bin/phpunit --configuration phpunit.xml
              env:
                  DB_PORT: ${{ job.services.mysql.ports['3306'] }}
