name: PHP 8.0 Tests

on: [ push, pull_request ]

jobs:
    phpunit:
        name: "PHP ${{ matrix.php }} Tests"
        runs-on: ubuntu-20.04

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_DATABASE: UNIT3D
                    MYSQL_PASSWORD: UNIT3D
                    MYSQL_USER: UNIT3D
                ports:
                    - 3306

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 1

            - name: Setup PHP 8.0
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  tools: phpunit
                  extensions: gd, json, mbstring, mysql, dom, fileinfo, xml, xsl, zip, curl, bcmath, intl
                  coverage: none

            - name: Install Composer Dependencies
              run: composer install

            - name: Copy UNIT3D CI Environment
              run: cp .env.testing .env

            - name: Generate UNIT3D Key
              run: php artisan key:generate

            - name: Run UNIT3D Migrations And Seed Them
              run: php artisan migrate --seed
              env:
                  DB_PORT: ${{ job.services.mysql.ports['3306'] }}

            - name: Run Testsuite
              run: ./vendor/bin/phpunit --env=testing
