name: PHP 8.0 Tests

on: [ push, pull_request ]

jobs:
    phpunit:
        name: "PHP ${{ matrix.php }} Tests"
        runs-on: ubuntu-20.04

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_DATABASE: UNIT3D
                    MYSQL_USER: UNIT3D
                    MYSQL_PASSWORD: UNIT3D
                    MYSQL_ROOT_PASSWORD: UNIT3D
                ports:
                    - 33306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 1

            - name: Verify MySQL Connection
              run: |
                mysql --version
                sudo apt-get install -y mysql-client
                mysql --host 127.0.0.1 --port 33306 -uUNIT3D -pUNIT3D -e "SHOW DATABASES"

            - name: Setup PHP 8.0
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.0'
                tools: phpunit
                extensions: gd, json, mbstring, mysql, dom, fileinfo, xml, xsl, zip, curl, bcmath, intl
                coverage: none

            - name: Install Composer Dependencies
              run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

            - name: Copy Environment File
              run: php -r "file_exists('.env') || copy('.env.github', '.env');"

            - name: Generate Application Key And Clear Caches
              run: |
                php artisan key:generate
                php artisan cache:clear
                php artisan config:clear

            - name: Directory Permissions
              run: chmod -R 777 storage bootstrap/cache

            - name: Execute Tests (Unit and Feature) via PHPUnit
              env:
                DB_CONNECTION: mysql
                DB_DATABASE: UNIT3D
                DB_USERNAME: UNIT3D
                DB_PASSWORD: UNIT3D
                DB_PORT: 33306
              run: |
                php artisan migrate
                vendor/bin/phpunit
